# - name: Add jessie-backports repository
#   apt_repository:
#     repo: deb http://ftp.debian.org/debian stable-backports main
#     state: present
#
# - name: Update cache
#   apt:
#     update_cache: yes
#
# - name: Install Kernel 4.
#   apt:
#     name: linux-image-amd64
#     state: latest
#     force: yes
#     force_apt_get: yes
#     default_release: stable-backports
#     update_cache: yes
#     autoclean: yes

 - name: Update cache
   apt:
     update_cache: yes

 - name: Install packages
   apt:
     name: "{{ packages }}"
     update_cache: yes
   vars:
     packages:
     - mc
     - bc
     - bind9
     - nscd
     - git
     - make
     - gcc
   tags:
   - packages

 - name: Get new kernel
   get_url:
     url: "{{ item }}"
     dest: /root/
   with_items:
     - https://storage.yandexcloud.net/xvostt/linux-headers-4.3.0-040300_4.3.0-040300.201511020949_all.deb
     - https://storage.yandexcloud.net/xvostt/linux-headers-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
     - https://storage.yandexcloud.net/xvostt/linux-image-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
   tags:
   - kernel

 - name: Install a .deb package from the blog.
   apt:
     deb: "{{ item }}"
   with_items:
     - linux-headers-4.3.0-040300_4.3.0-040300.201511020949_all.deb
     - linux-headers-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
     - linux-image-4.3.0-040300-generic_4.3.0-040300.201511020949_amd64.deb
   register: update

 - name: Reboot to apply new kernel
   reboot:
     reboot_timeout: 120
   when: update is changed
   tags:
   - kernel

 - name: Get git repo 3proxy
   git:
     repo: https://github.com/z3APA3A/3proxy.git
     dest: /root/3proxy
     force: yes
   register: getgit

 - name: Make 3proxy
   shell: cd /root/3proxy && make -f Makefile.Linux
   args:
     executable: /bin/bash
   ignore_errors: true
   when: getgit is changed

 - name: mkdir /home/3proxy
   file:
     path: '/home/{{ item }}'
     state: directory
     mode: 0755
     owner: nobody
     group: nogroup
   with_items:
     - '3proxy'

 - name: Copy 3proxy binary
   shell: cp -f /root/3proxy/bin/3proxy /home/3proxy/3proxy
   when: getgit is changed

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'listen-on-v6'
     replace: 'listen-on'
   tags:
   - dns

 - name: Change bind's listening ips
   replace:
     path: /etc/bind/named.conf.options
     regexp: 'any'
     replace: '127.0.0.1'
   tags:
   - dns

 - name: Change nameservers
   replace:
     path: /etc/network/interfaces
     regexp: '8.8.8.8'
     replace: '127.0.0.1'
   tags:
     - dns

 - name: Copy resolv.conf
   copy:
     src: resolv.conf
     dest: /etc/resolv.conf
     mode: 0744
   tags:
   - dns

 - name: Restart bind9 service
   service:
     name: bind9
     state: restarted
   tags:
   - dns
